### ISSUE TITLE
cannot create event stream

### ISSUE THREAD

**Issue by jonarmani** [shutton/webex-rust#28] opened 2023-09-07 17:33 UTC
The "hello-world" example works for me (sending a message), but not the "auto-reply" one. It errors on creating the event stream:

```rs
let mut event_stream = webex.event_stream().await.expect("event stream");
```

At runtime: `thread 'main' panicked at 'event stream: Error(Msg("Can't decode devices reply: failed to parse reply"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', src/main.rs:8:55`

Authentication is not the issue, evident from the things that work like sending messages and listing rooms. But I'd like to be able to read messages, which is why I'm creating an event stream.

**Comment by grnmeira** [comment] 2023-09-07 19:11
Hi @jonarmani. Thanks for reporting this. I just gave it a try from top of master but I can't reproduce your issue here on my side, but I have a couple of questions because I may have an idea of what's going on.

The user that created the bot on developer.webex.com, has that user ever been logged in to Webex? If so, was it only using the web client?

Also, do you have any tools like mitmproxy or Fiddler available so you can show us the HTTP requests and responses that happen during the process? And careful here not to make your bot token public.

**Comment by grnmeira** [comment] 2023-09-07 19:18
I actually can reproduce the issue now, let me look into this and I can place a PR. @aknarts can you assign me to this issue please?

**Comment by grnmeira** [comment] 2023-09-09 14:46
@jonarmani, can you try this branch: https://github.com/grnmeira/webex-rust/tree/optinal-device-settings? Let me know if that works.

If that doesn't work, can you please run the example using env_logger. You can just do a `cargo add env_logger`, add an `env_logger::init();` into the example's main function, and add the RUST_LOG=debug environment variable. That should print log lines with more details of what's going on.

**Comment by grnmeira** [comment] 2023-09-14 13:36
There's a couple of different ways to resolve this. Here's a draft PR: https://github.com/shutton/webex-rust/pull/29/files

**Comment by jonarmani** [comment] 2023-09-15 00:20
> @jonarmani, can you try this branch: https://github.com/grnmeira/webex-rust/tree/optinal-device-settings? Let me know if that works.
> 
> If that doesn't work, can you please run the example using env_logger. You can just do a `cargo add env_logger`, add an `env_logger::init();` into the example's main function, and add the RUST_LOG=debug environment variable. That should print log lines with more details of what's going on.

That branch works! Thanks!

**Comment by grnmeira** [comment] 2023-10-07 13:45
PR #29 merged, I imagine we can close this.

**Closed** 2023-11-13 00:18 UTC
